# Generated by Django 3.1.6 on 2021-02-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='coffee_images')),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('in_stock', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
