# Generated by Django 3.1.6 on 2021-02-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_auto_20210223_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatinghours',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operatinghours',
            name='weekday',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=3),
        ),
    ]
