# Generated by Django 3.1.6 on 2021-02-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_auto_20210223_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghours',
            name='from_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='operatinghours',
            name='to_hour',
            field=models.TimeField(null=True),
        ),
    ]
