# Generated by Django 3.1.6 on 2021-02-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_auto_20210224_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='image',
            field=models.ImageField(blank=True, upload_to='store_images'),
        ),
    ]
