# Generated by Django 3.1.6 on 2021-02-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_storelocation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hour', models.TimeField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Store Hours',
                'ordering': ('day', 'from_hour'),
            },
        ),
        migrations.DeleteModel(
            name='OperatingHours',
        ),
        migrations.AlterModelOptions(
            name='storelocation',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Store Locations'},
        ),
    ]
