# Generated by Django 3.1.6 on 2021-02-12 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
        ('authapp', '0002_coffcart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoffCart',
            new_name='Cart',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart'},
        ),
    ]
