# Generated by Django 3.1.6 on 2021-08-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_user_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Stripe ID'),
        ),
    ]
